### ISSUE TITLE
500 instead of 404

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/buda-iiif-server#11]
When reaching for a non-existing image like

http://iiif.bdrc.io/image/v2/bdr:V23703_I1521::152106isfjgoeirf.jpg/full/full/0/default.jpg

the server returns a 500 error instead of a 404. The [spec](https://iiif.io/api/image/2.1/#server-responses) is quite clear that it should be a 404

**Comment by MarcAgate** [comment]
this is fixed as of commit 859630d . However while this http://localhost:8080/image/v2/bdr:V29199_I5166::51660001.tif/info.json leads to 403 "Insufficient rights" locally (in dev), it returns 500 on ec2.

**Comment by MarcAgate** [comment]
issue with 500 code instead of 403 has been fixed. http://iiif.bdrc.io/image/v2/bdr:V29199_I5166::51660001.tif/info.json

**Comment by eroux** [comment]
cool, thanks!
