### ISSUE TITLE
public cache claim for open access images

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/buda-iiif-server#15]
For all the images that don't require authentication to be accessed (including the 20 first and final pages of a FairUse work), the cache control mechanism should advertise the image to be `public` (see [rfc7234](https://greenbytes.de/tech/webdav/rfc7234.html#caching.authenticated.responses)). I think images restricted in China could have that too...

**Comment by eroux** [comment]
the others should have a `private` indication

**Comment by MarcAgate** [comment]
This was implemented for 
- ldspdi (https://github.com/BuddhistDigitalResourceCenter/lds-pdi/commit/b7ec9921c9c9f13ac6be3d08b67d46412fac9008) 
- iiifserv (https://github.com/BuddhistDigitalResourceCenter/buda-iiif-server/commit/f5a7ed01473020a853d1928cdf1cf2d3001e4983)
- iiifpres (https://github.com/BuddhistDigitalResourceCenter/buda-iiif-presentation/commit/4ef1a82b464017e17776fec423c5537dbe015f58)

**Comment by eroux** [comment]
thanx!
