### ISSUE TITLE
client cache headers

### ISSUE THREAD

**Issue by eroux** [BuddhistDigitalResourceCenter/buda-iiif-server#4]
I don't know if it's relevant in all hymir use cases, but it definitely is in ours: we want to instruct web browsers to cache images and `info.json`s. Currently there is no http cache instructions, there should be at least a configurable `max-age`. In our case it can be very large, the images more or less never change.

**Comment by MarcAgate** [comment]
Configurable max-age (through external application.yml) was implemented (HeaderFilter) in commit 7376a92

**Comment by eroux** [comment]
There is an oddity in firefox we're tracking (it doesn't cache some images). It may (or may not) be due to the absence of `public` (or `private`) in the header, could we add publid and have

```
Cache-control: public, max-age=31536000
```

? (I think `private` should be used when we'll serve restricted images in the future)
